// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2_nwg1xzydoKlbdgUpcdwo_EUpzIU8Fs',
    appId: '1:1067174062177:web:178724cd8301c5abec2220',
    messagingSenderId: '1067174062177',
    projectId: 'chat-app-firebase-9f53c',
    authDomain: 'chat-app-firebase-9f53c.firebaseapp.com',
    storageBucket: 'chat-app-firebase-9f53c.appspot.com',
    measurementId: 'G-YHRESB9LYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeg3euwbfzBsPwAeEhqHTUg3BUOd4L0D4',
    appId: '1:1067174062177:android:baaf1283df4e52c2ec2220',
    messagingSenderId: '1067174062177',
    projectId: 'chat-app-firebase-9f53c',
    storageBucket: 'chat-app-firebase-9f53c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2fZIOYOBxqknedRPSAt5jcCjA_XMIMTk',
    appId: '1:1067174062177:ios:83dee04af81b21c8ec2220',
    messagingSenderId: '1067174062177',
    projectId: 'chat-app-firebase-9f53c',
    storageBucket: 'chat-app-firebase-9f53c.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2fZIOYOBxqknedRPSAt5jcCjA_XMIMTk',
    appId: '1:1067174062177:ios:83dee04af81b21c8ec2220',
    messagingSenderId: '1067174062177',
    projectId: 'chat-app-firebase-9f53c',
    storageBucket: 'chat-app-firebase-9f53c.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2_nwg1xzydoKlbdgUpcdwo_EUpzIU8Fs',
    appId: '1:1067174062177:web:1fb941168512da72ec2220',
    messagingSenderId: '1067174062177',
    projectId: 'chat-app-firebase-9f53c',
    authDomain: 'chat-app-firebase-9f53c.firebaseapp.com',
    storageBucket: 'chat-app-firebase-9f53c.appspot.com',
    measurementId: 'G-E5QHPEYKV9',
  );
}
